dbt_servier:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'mydbt.db'
      schema: 'main'
      schema_directory: './'
      schemas_and_paths:
        main: 'mydbt.db'
